websnap.title=Web Snapshot
websnap.label=WebSnap
websnap.version=8.2.0
websnap.icon=<i class='fas fa-camera'></i>
websnap.description=browser-accurate snapshot
websnap.fileName=Custom File Name
websnap.fileName.description=Default is `web-snapshot-{timestamp}`.
websnap.fileExtension=File Extension
websnap.fileExtension.pdf=PDF
websnap.fileExtension.png=PNG
websnap.fileExtension.webp=WebP
websnap.fileExtension.jpeg=JPEG
websnap.gotenberg.debugMode=Debug Mode
websnap.gotenberg.debugMode.description=Log network activity with Gotenberg server. This is useful for troubleshooting connection or rendering issues.
websnap.gotenberg.title=Gotenberg Server
websnap.gotenberg.scheme=Scheme
websnap.gotenberg.domain=Domain or Ip Address
websnap.gotenberg.port=Port
websnap.gotenberg.docs=Gotenberg Docs
websnap.gotenberg.connection.test=Test Connection
websnap.gotenberg.connection.ok=Gotenberg server connected.
websnap.gotenberg.connection.fail=Unable to establish connection.
websnap.gotenberg.settings.title=Snapshot Settings
websnap.gotenberg.settings.description=Layout settings to take the snapshot.
websnap.gotenberg.screen.width=Screen Width
websnap.gotenberg.screen.width.description=Screen width in pixels.
websnap.gotenberg.screen.height=Screen Height
websnap.gotenberg.screen.height.description=Screen height in pixels.
websnap.gotenberg.urlToPdf.settings=PDF Settings
websnap.gotenberg.urlToPdf.docs.link=<a href='https://gotenberg.dev/docs/convert-with-chromium/convert-url-to-pdf#rendering-behavior' target='_blank'>https://gotenberg.dev/docs/convert-with-chromium/convert-url-to-pdf#rendering-behavior</a>
websnap.gotenberg.urlToPdf.mediaType=CSS Media Type
websnap.gotenberg.urlToPdf.mediaType.screen=Screen
websnap.gotenberg.urlToPdf.mediaType.print=Print
websnap.gotenberg.urlToPdf.printBackground=Print Background
websnap.gotenberg.urlToPdf.printBackground.description=Includes background graphics/colors from the HTML.
websnap.gotenberg.urlToPdf.landscape=Landscape
websnap.gotenberg.urlToPdf.landscape.description=Sets the paper orientation to landscape.
websnap.gotenberg.urlToPdf.paper.width=Paper Width
websnap.gotenberg.urlToPdf.paper.width.description=Paper width. Standard units supported (in, pt, cm). Default is inches.
websnap.gotenberg.urlToPdf.paper.height=Paper Height
websnap.gotenberg.urlToPdf.paper.height.description=Paper height. Standard units supported (in, pt, cm). Default is inches.
websnap.gotenberg.urlToPdf.margin.top=Top Margin
websnap.gotenberg.urlToPdf.margin.top.description=Top margin. Standard units supported (in, pt, cm). Default is inches.
websnap.gotenberg.urlToPdf.margin.bottom=Bottom Margin
websnap.gotenberg.urlToPdf.margin.bottom.description=Bottom margin. Standard units supported (in, pt, cm). Default is inches.
websnap.gotenberg.urlToPdf.margin.left=Left Margin
websnap.gotenberg.urlToPdf.margin.left.description=Left margin. Standard units supported (in, pt, cm). Default is inches.
websnap.gotenberg.urlToPdf.margin.right=Right Margin
websnap.gotenberg.urlToPdf.margin.right.description=Right margin. Standard units supported (in, pt, cm). Default is inches.
websnap.gotenberg.urlToPdf.scale=Scale
websnap.gotenberg.urlToPdf.scale.description=Zoom scaling.
websnap.gotenberg.urlToImage.settings=Image Settings
websnap.gotenberg.urlToImage.docs.link=<a href='https://gotenberg.dev/docs/convert-with-chromium/screenshot-url#rendering-behavior' target='_blank'>https://gotenberg.dev/docs/convert-with-chromium/screenshot-url#rendering-behavior</a>
websnap.gotenberg.urlToImage.clip=Clip
websnap.gotenberg.urlToImage.clip.description=Define whether to clip the screenshot according to the device dimensions.
websnap.gotenberg.urlToImage.format=Compression format
websnap.gotenberg.urlToImage.jpegQuality=Compression quality
websnap.gotenberg.urlToImage.jpegQuality.description=Quality range is 0-100.
websnap.gotenberg.urlToImage.omitBackground=Omit Background
websnap.gotenberg.urlToImage.omitBackground.description=Hides the default white background to allow transparency.
websnap.gotenberg.urlToImage.optimizeForSpeed=Optimize for Speed
websnap.gotenberg.urlToImage.optimizeForSpeed.description=Optimizes image encoding for speed rather than resulting file size.